services:
  - type: web
    name: feed-dunia-client
    env: static
    rootDir: client      # Hapa inaelekea kwenye folder la client
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: feed-dunia-server
    env: node
    rootDir: server      # Hapa inaelekea kwenye folder la server
    buildCommand: npm install
    startCommand: node index.js
