services:
  - type: web
    name: feed-the-world
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
